Mounts
TykTechnologies/tyk-helm-chart pull request #133
Opened 2021-06-18 16:01 UTC by zalbiraw

2021-06-21 09:06 UTC, abhishiekgowtham commented
Hey @zalbiraw! I've made some changes to the PR, please review them. If everything looks good, we can merge.

2021-06-23 07:19 UTC, abhishiekgowtham requested changes
Thanks @zalbiraw! Please update the files based on the feedback.

2021-06-23 07:19 UTC, abhishiekgowtham commented on tyk-headless/values.yaml
> +    #   mountPath: /dev/null
I think it's better to have a single generic example on how to mount files which can be used for all components. I don't think we need to do this for each component. 

Same thing for all other charts too.

2021-06-23 17:26 UTC, abhishiekgowtham approved these changes
/lgtm

@vesko-tyk Please review again before merging.

2021-06-24 08:30 UTC, vesko-tyk approved these changes
Looks good, thanks!

2021-06-24 08:30 UTC, merged