[TD-544] Tyk Dashboard Helm Chart
TykTechnologies/tyk-helm-chart pull request #160
Opened 2021-09-20 14:12 UTC by abhishiekgowtham

As planned, this PR splits the dashboard component into its own individual chart.

2021-09-29 08:32 UTC, vesko-tyk requested changes
@abhishiekgowtham I've reviewed your PR and have left some comments. Please let me know know your thoughts on it. Thanks!

2021-10-03 10:29 UTC, abhishiekgowtham commented on charts/dashboard/docs/doc.yaml
> +  name: dashboard
Commit `7f4f891` should address it.

2021-10-03 10:31 UTC, abhishiekgowtham commented on charts/dashboard/templates/deployment.yaml
> +{{- if .Values.enabled -}}
This is to render the templates conditionally. It's enabled by default (set to `true`). When importing these charts into an umbrella chart, it gives the parent chart an option.

2021-10-03 10:31 UTC, abhishiekgowtham commented on charts/dashboard/templates/deployment.yaml
> +        imagePullPolicy: {{ .Values.image.pullPolicy }}
Have addressed this issue in `7f4f891`

2021-10-03 10:32 UTC, abhishiekgowtham commented on charts/dashboard/templates/deployment.yaml
> +                key: DashLicense
This should be resolved by commit `7f4f891`.

2021-11-01 09:10 UTC, abhishiekgowtham commented on charts/dashboard/docs/doc.yaml
> +  name: dashboard
Fixed in ba872ec

2021-11-01 09:10 UTC, abhishiekgowtham commented on charts/dashboard/templates/ingress.yaml
> +spec:
Fixed in ba872ec

2021-11-10 10:37 UTC, alephnull approved these changes
This looks for a first cut.

2021-11-10 10:43 UTC, gwotg approved these changes
Thanks @abhishiekgowtham! LGTM

2021-11-10 10:47 UTC, gwotg commented
> Thanks @abhishiekgowtham! LGTM

Do we plan to get rid of those smoke tests errors before merging?

2021-11-10 11:42 UTC, abhishiekgowtham commented on charts/dashboard/scripts/init.sh
> +while [[ $(kubectl get po -n {{ .Release.Namespace }} --selector=app.kubernetes.io/component=tyk-dashboard -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do sleep 10; d
yes, it does since that label exists for all dashboard pods.

2021-11-10 11:44 UTC, abhishiekgowtham commented
> > Thanks @abhishiekgowtham! LGTM
> 
> Do we plan to get rid of those smoke tests errors before merging?

No, that's a different issue and not part of this PR. It'll be tackled differently once all (parent and child) charts are in place.

2021-11-18 11:43 UTC, ermirizio approved these changes
Looks Good!

2021-11-24 23:05 UTC, vesko-tyk approved these changes
LGTM!

2021-11-25 12:27 UTC, merged