Make bootstrap job images configurable
TykTechnologies/tyk-helm-chart pull request #291
Opened 2023-10-01 07:07 UTC by Guitarkalle

Make bootstrap job images configurable in tyk-pro chart

## Description
Restructured values file a bit to make it possible to also add configuration for bootstrap job images. 

## Related Issue

https://github.com/TykTechnologies/tyk-helm-chart/issues/290

## Motivation and Context
If using private docker registries with mirrored images it is not possible to pull from dockerhub, therefor the images in the bootstrap job are needed to be configurable, as all other images in the chart.

## Test Coverage For This Change
Did helm template and compared with previous version. Only difference is an autogenerated password, TYK_PASS.

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). If PRing from your fork, don't come from your `master`!
- [x] Make sure you are making a pull request against our **`master` branch** (left side). Also, it would be best if you started *your change* off *our latest `master`*.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-03 09:35 UTC, buraksekili approved these changes
LGTM! Thank you @Guitarkalle, i'll move this ticket to QA and once the testing is finished, the pr will be merged. thanks again

2023-11-02 07:31 UTC, komalsukhani requested changes

2023-11-02 07:31 UTC, komalsukhani commented on tyk-pro/values.yaml
> +      tag: latest
```suggestion
      tag: v1.5.1
```

2023-11-02 07:31 UTC, komalsukhani commented on tyk-pro/values.yaml
> +      tag: latest
```suggestion
      tag: v1.5.1
```

2023-11-02 07:32 UTC, komalsukhani commented
@Guitarkalle Can you update your PR to use v1.5.1 instead?
If not, maybe I can push necessary commits.

2023-11-02 11:05 UTC, komalsukhani commented
@Guitarkalle Sorry. I had to raise another PR based on yours.
This PR urgently needed to be tested and required few changes.
I wasn't sure if it's okay for you if I committed changes directly on your PR.

2023-11-08 06:22 UTC, komalsukhani commented
Closing in favor of #293

2023-11-08 06:22 UTC, closed without merging