updates chart for new universal redis client
TykTechnologies/tyk-helm-chart pull request #69
Opened 2020-09-04 21:12 UTC by asoorm

resolves #68

2020-09-06 15:32 UTC, vesko-tyk commented on values.yaml
> +  license: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhbGxvd2VkX25vZGVzIjoiOGU4NWFjZTUtNGRjOC00OTk1LTRkNzUtNWI4YTM2YzA4ZTJmLDViMDAzYzI1LTg3ZjYtNDIyZC00ODBhLWRiMGNjZDdhNjBlYyw2NWM4NDhhMy0xYWU4LTRhNzQtNG
@asoorm Could you remove this please? The license should not be exposed here. Thanks

2020-09-07 12:02 UTC, excieve requested changes
Nice, thanks! I'd suggest using a YAML list where variable is logically always a list of items for better usability.

2020-09-09 20:48 UTC, drpebcak commented on values.yaml
> +    addrs: "tyk-redis-master.tyk-ingress.svc.cluster.local:6379"
I agree the list is easier, if you are using values.yaml. If you are using `--set`, it becomes a pain to access elements of the list.

2020-09-09 20:48 UTC, drpebcak commented on values.yaml
> +    addrs: "tyk-redis-master.tyk-ingress.svc.cluster.local:6379"
(personally I use values.yaml, so I'm all for that)

2020-09-09 20:49 UTC, joshblakeley commented on values.yaml
> +    addrs: "tyk-redis-master.tyk-ingress.svc.cluster.local:6379"
Thanks Taylor - i'm willing to ignore the --set crowd also

2020-09-17 16:15 UTC, drpebcak commented
Any movement on this?

2020-09-24 06:33 UTC, asoorm commented
> Any movement on this?

Hello - I will try to make changes today.

2020-11-07 20:48 UTC, asoorm commented
@excieve PTAL

2020-11-08 08:53 UTC, asoorm commented
After further testing, I found a couple of issues with erroneous log messages:

```
time="Nov 08 08:52:25" level=error msg="Error trying to get TTL: MOVED 609 10.244.0.60:6379"
time="Nov 08 08:52:26" level=error msg="Redis health check failed" error="storage: Redis is either down or ws not configured" liveness-check=true prefix=main
time="Nov 08 08:52:34" level=error msg="Error trying to get TTL: MOVED 609 10.244.0.60:6379"
time="Nov 08 08:52:36" level=error msg="Redis health check failed" error="storage: Redis is either down or ws not configured" liveness-check=true prefix=main
time="Nov 08 08:52:40" level=error msg="Error trying to get TTL: MOVED 609 10.244.0.60:6379"
time="Nov 08 08:52:40" level=error msg="Could not EXPIRE key: MOVED 609 10.244.0.60:6379"
```

Moving to draft till I figure this out.

2021-02-18 12:13 UTC, vesko-tyk commented
This is now implemented in this PR:https://github.com/TykTechnologies/tyk-helm-chart/pull/73

2021-02-18 12:13 UTC, closed without merging