Roll using rand method instead of template hash
TykTechnologies/tyk-helm-chart pull request #91
Opened 2021-03-15 15:47 UTC by joshblakeley

The previous roll method caused recursion errors because of self referencing templates.

Instead to self roll a dep you can use the rand method detailed in the helm docs here: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

We should also document the behaviour for helm upgrade that you get because of this since before someone would need the deprecated --recreate-pods flag to roll their pods

2021-03-15 18:11 UTC, drpebcak commented
What resources are changing without causing these pods to get recreated? The configmaps? If that's the case, why not just reference a checksum of the configmap instead? Would be better than forcing re-rolls always, when it might not be needed.

2021-03-15 18:15 UTC, joshblakeley commented
The original intention seems to have just been to roll when the deployment itself was modified not any other file. I've jsut followed the recommended approach for this from the Helm docs but would welcome input from @excieve and @vesko-tyk

2021-03-15 18:50 UTC, drpebcak commented
For a deployment the default behavior of kubernetes would already cause the pods to re-roll if anything inside the deployment object is changed.

2021-03-15 22:12 UTC, excieve requested changes
The idea was to hash the configmaps, not the deployments. It seems the includes in the annotations are referencing the deployment yamls, which is of course wrong.

Rolling each time is not great as noted in this thread. Would be great if the PR instead referenced correct templates.

I will also reopen the internal ticket that tracked the original change.

2021-03-16 10:05 UTC, joshblakeley commented
Closing so this can be addressed by the devops team

2021-03-16 10:05 UTC, closed without merging